version: '3.8'

services:
  mongodb:
    image: mongo:7.0.8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./deployment/init-db:/docker-entrypoint-initdb.d
    networks:
      - mongo_network
  challenge:
    build: deployment
    image: tui/meta-challenge:latest
    container_name: challenge
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - mongo_network
    environment:
     - MONGO_DB_URI=mongodb://mongodb:27017

volumes:
  mongodb_data:

networks:
  mongo_network:
    driver: bridge
